name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases mac and windows
        run: |
          npm exec electron-builder -- --publish=never --mac

      - name: Upload mac arm64.app
        uses: actions/upload-artifact@v3
        with:
          name: Har-Visual-Native-mac-arm64.app
          path: ./release/build/mac-arm64/Har-Visual-Native.app

      - name: Upload mac .app
        uses: actions/upload-artifact@v3
        with:
          name: Har-Visual-Native.app
          path: ./release/build/mac/Har-Visual-Native.app

      # - name: Publish releases mac and windows
      #   run: |
      #     npm exec electron-builder -- --publish=never --win

      # - name: Upload .exe
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Har-Visual-Native.exe
      #     path: ./release/build/win-unpacked/Har-Visual-Native.exe
